{% set name = "yaqd-fakes" %}
{% set version = "2022.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 90ad724cca5fe6843740fae8b194e888b693331295f2edd45d77cecfac3f8b3a

build:
  number: 0
  noarch: python
  entry_points:
    - yaqd-fake-continuous-hardware = yaqd_fakes._fake_continuous_hardware:FakeContinuousHardware.main
    - yaqd-fake-discrete-hardware = yaqd_fakes._fake_discrete_hardware:FakeDiscreteHardware.main
    - yaqd-fake-triggered-sensor = yaqd_fakes._fake_triggered_sensor:FakeTriggeredSensor.main
    - yaqd-fake-has-turret = yaqd_fakes._fake_has_turret:FakeHasTurret.main
    - yaqd-fake-sensor = yaqd_fakes._fake_sensor:FakeSensor.main
    - yaqd-fake-spectrometer = yaqd_fakes._fake_spectrometer:FakeSpectrometer.main
    - yaqd-fake-camera = yaqd_fakes._fake_camera:FakeCamera.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python >=3.7
    - yaqd-core >=2022.3.0
  run:
    - python >=3.7
    - yaqd-core >=2022.3.0

test:
  imports:
    - yaqd_fakes
  commands:
    - pip check
    - yaqd-fake-continuous-hardware --help
    - yaqd-fake-discrete-hardware --help
    - yaqd-fake-triggered-sensor --help
    - yaqd-fake-has-turret --help
    - yaqd-fake-sensor --help
    - yaqd-fake-spectrometer --help
    - yaqd-fake-camera --help
  requires:
    - pip
    - numpy

about:
  home: https://yaq.fyi
  dev_url: https://gitlab.com/yaq/yaq-python
  summary: fake yaq daemons, for testing purposes
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
