{% set name = "yaqd-fakes" %}
{% set version = "2021.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c8325532bcae1171709b2291124bc66359c4297827579b741a92abd21e452148

build:
  number: 0
  noarch: python
  entry_points:
    - yaqd-fake-continuous-hardware = yaqd_fakes._fake_continuous_hardware:FakeContinuousHardware.main
    - yaqd-fake-discrete-hardware = yaqd_fakes._fake_discrete_hardware:FakeDiscreteHardware.main
    - yaqd-fake-triggered-sensor = yaqd_fakes._fake_triggered_sensor:FakeTriggeredSensor.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python >=3.7
    - yaqd-core >=2020.05.1
  run:
    - python >=3.7
    - yaqd-core >=2020.05.1

test:
  imports:
    - yaqd_fakes
  commands:
    - pip check
    - yaqd-fake-continuous-hardware --help
    - yaqd-fake-discrete-hardware --help
    - yaqd-fake-triggered-sensor --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  dev_url: https://gitlab.com/yaq/yaq-python
  summary: fake yaq daemons, for testing purposes
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
