{% set name = "yaqd-fakes" %}
{% set version = "2023.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 11372b1770c108a44ac4b782930c0e7f33d2ae7441aa931909e618dc8c22633f

build:
  number: 1
  noarch: python
  entry_points:
    - yaqd-fake-continuous-hardware = yaqd_fakes._fake_continuous_hardware:FakeContinuousHardware.main
    - yaqd-fake-discrete-hardware = yaqd_fakes._fake_discrete_hardware:FakeDiscreteHardware.main
    - yaqd-fake-triggered-sensor = yaqd_fakes._fake_triggered_sensor:FakeTriggeredSensor.main
    - yaqd-fake-has-turret = yaqd_fakes._fake_has_turret:FakeHasTurret.main
    - yaqd-fake-sensor = yaqd_fakes._fake_sensor:FakeSensor.main
    - yaqd-fake-spectrometer = yaqd_fakes._fake_spectrometer:FakeSpectrometer.main
    - yaqd-fake-camera = yaqd_fakes._fake_camera:FakeCamera.main
    - yaqd-fake-furnace = yaqd_fakes._fake_furnace:FakeFurnace.main
    - yaqd-fake-has-transformed-position =  yaqd_fakes._fake_has_transformed_position:FakeHasTransformedPosition.main

  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - hatchling
    - python >=3.7
    - yaqd-core >=2022.6.0
  run:
    - python >=3.7
    - yaqd-core >=2022.6.0

test:
  imports:
    - yaqd_fakes
  commands:
    - pip check
    - yaqd-fake-continuous-hardware --help
    - yaqd-fake-discrete-hardware --help
    - yaqd-fake-triggered-sensor --help
    - yaqd-fake-has-turret --help
    - yaqd-fake-sensor --help
    - yaqd-fake-spectrometer --help
    - yaqd-fake-camera --help
  requires:
    - pip
    - numpy

about:
  home: https://yaq.fyi
  dev_url: https://gitlab.com/yaq/yaq-python
  summary: fake yaq daemons, for testing purposes
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
