{% set name = "yaqd-fakes" %}
{% set version = "2020.7.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 74cb5ecfd3e5d160520faf6f2f54c771e469d201bc673a2c6e48c3e29bd49c75

build:
  number: 0
  noarch: python
  entry_points:
    - yaqd-fake-continuous-hardware = yaqd_fakes._fake_continuous_hardware:FakeContinuousHardware.main
    - yaqd-fake-discrete-hardware = yaqd_fakes._fake_discrete_hardware:FakeDiscreteHardware.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python >=3.7
    - yaqd-core >=2020.05.1
  run:
    - python >=3.7
    - yaqd-core >=2020.05.1

test:
  imports:
    - yaqd_fakes
  commands:
    - pip check
    - yaqd-fake-continuous-hardware --help
    - yaqd-fake-discrete-hardware --help
  requires:
    - pip

about:
  home: https://gitlab.com/yaq/yaqd-fakes
  summary: fake yaq daemons, for testing purposes
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
